spring:
  application:
    name: turbine

server:
  port: 8090

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

hystrix:
  dashboard:
    proxy-stream-allow-list: '*'

turbine:
  app-config: customer-service,order-service
  cluster-name-expression: new String("default")