spring:
  application:
    name: api-gateway

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

zuul:
  ignoredServices: '*'
  sensitive-headers: Cookie,Set-Cookie
  routes:
    users:
      path: /users/**
      serviceId: auth-service
      stripPrefix: false

    oauth:
      path: /oauth/**
      serviceId: auth-service
      stripPrefix: false

    customers:
      path: /customers/**
      serviceId: customer-service
      stripPrefix: false

    products:
      path: /products/**
      serviceId: product-catalog-service
      stripPrefix: false

    orders:
      path: /orders/**
      serviceId: order-service
      stripPrefix: false
