CREATE TABLE IF NOT EXISTS users(
    id uuid NOT NULL PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS roles(
    id SERIAL NOT NULL PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS users_roles(
    user_fk uuid NOT NULL REFERENCES users,
    role_fk INTEGER NOT NULL REFERENCES roles
);