spring:
  application:
    name: customer-service

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/customer_service
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

server:
  port: 8081

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

security:
  oauth2:
    client:
      client-id: customer-service
      client-secret: customer-service-secret
      access-token-uri: http://localhost:9000/oauth/token
      scope: server
    resource:
      token-info-uri: http://localhost:9000/oauth/check_token

feign:
  hystrix:
    enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 2500

logging:
  level:
    com:
      mikhailkarpov:
        customers:
          service:
            AuthService: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: '*'
