spring:
  application:
    name: order-service

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/order_service
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

security:
  oauth2:
    client:
      client-id: order-service
      client-secret: order-service-secret
      access-token-uri: http://localhost:9000/oauth/token
    resource:
      token-info-uri: http://localhost:9000/oauth/check_token

feign:
  hystrix:
    enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 2500

logging:
  level:
    com:
      mikhailkarpov:
        orders:
          service:
            ProductService: DEBUG