spring:
  application:
    name: shopping-cart-service

  cache:
    type: redis
    redis:
      cache-null-values: false
      time-to-live: 10m

  redis:
    host: localhost
    port: 6379
    password:

server:
  port: 8084

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

security:
  oauth2:
    client:
      client-id: order-service
      client-secret: order-service-secret
      access-token-uri: http://localhost:9000/oauth/token

feign:
  hystrix:
    enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 2500

logging:
  level:
    com:
      mikhailkarpov:
        shoppingcart:
          service:
            ProductService: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: '*'
